spring.application.name=main-server
server.port=8888

spring.cloud.config.server.prefix=/config
spring.cloud.config.server.native.search-locations=file:../config-server
spring.cloud.config.server.search-paths=config


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost